language: python
python:
    - "3.6"
before_install:
  - pip install codecov
install:
    - pip install -r requirements.txt
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - python tests/tests_preprocessing_methods.py
  - python tests/tests_extract_features_methods.py
  - coverage run tests/tests_preprocessing_methods.py
  - coverage run tests/tests_extract_features_methods.py
after_success:
  - codecov -f hrvanalysis/extract_features.py hrvanalysis/preprocessing.py